# Generated by Django 6.1.1 on 2026-09-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='type',
            field=models.CharField(choices=[('item', 'Товар'), ('vacancy', 'Вакансия')], default='item', max_length=10, verbose_name='Тип'),
        ),
    ]
